### ISSUE TITLE
No hay fichero api

### ISSUE THREAD

**Issue by ghost** [kennbroorg/poorskeme#1]
Tras seguir los pasos al ejecutar el poorSKeme indica que no hay el fichero para la API donde poder introducir la generada.
¿Tiene que seguir algun formato concreto o es un fichero con la clave directamente?

poorSKeme$ python3 poorSKeme.py --help
Traceback (most recent call last):
  File "poorSKeme.py", line 534, in <module>
    with open(r'./API.yaml') as file:
FileNotFoundError: [Errno 2] No such file or directory: './API.yaml'

**Comment by KennBro** [comment]
Aquí está el archivo, está incluído en el repositorio...
![Repositorio](https://user-images.githubusercontent.com/32843687/177014962-790b3d5f-d1ae-4358-9bd1-16b4daf24aeb.png)
