### ISSUE TITLE
visulization error

### ISSUE THREAD

**Issue by vihari1729** [kennbroorg/poorskeme#2]
```
Traceback (most recent call last):
  File "poorSKeme.py", line 649, in <module>
    rc = process_json(args.file)
  File "poorSKeme.py", line 255, in process_json
    raise("JSON File not found")
TypeError: exceptions must derive from BaseException
```

i am getting visualization error like above once the json file is saved

**Comment by vihari1729** [comment]
the code is working only for mentioned address, not working for other errors

`AssertionError: Contract source code not verified -- NOTOK
`
getting above error for trying other wallet address

**Comment by KennBro** [comment]
This project don't work with wallets address. The mentioned address is a smart contract address.
